version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8008:8000"
    volumes:
      - ./:/app
    entrypoint: php artisan octane:frankenphp --max-requests=1

