version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8008:8000"
    volumes:
      - ./:/app/public
    command: "php /app/public/artisan octane:start"

